name: CI
on: push
jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Install modules
                run: yarn install
            -   name: Run tests
                run: yarn test
    release:
        name: Release
        needs: tests
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-18.04
        steps:
            -   uses: brpaz/action-semantic-release@v1
                with:
                    dry_run: false
                    branch: master
