name: CI
on: push
jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Install modules
                run: yarn install
            -   name: Run tests
                run: yarn test
    release:
        name: Release
        needs: tests
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Install modules
                run: yarn install
            -   name: Release new version
                run: yarn run release
                env:
                    NPM_TOKEN: ${{secrets.NPM_TOKEN}}
                    GH_TOKEN: ${{secrets.GH_TOKEN}}
